# Generated by Django 5.2.16 on 2026-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_featured_order_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
