# Generated by Django 5.2.16 on 2026-09-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_discount_ends_at_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
