# Generated by Django 5.2.16 on 2026-09-18 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('avatar_frame', models.CharField(choices=[('none', 'No Frame'), ('classic', 'Classic Pink'), ('teal_ring', 'Teal Ring'), ('gold_elite', 'Gold Elite'), ('neon_glow', 'Neon Glow'), ('royal_diamond', 'Royal Diamond')], default='none', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
